### ISSUE TITLE
Add flexibility to JWT token validation in openapi-security

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-rest-4j#105]
The openapi-security module, via the JwtVerifyHandler class, extracts and validates 2 JWT tokens:
1. Subject Token - located in the header in the Authorization header
2. Scope Token - located in the header in the X_Scope_token header

In both cases, the extracted claims, after validation, are stored in the AuditInfo, and made available to subsequent handlers in the handler chain.

The Scope Token is being extracted from the request and validated only if scope verification is enabled.

To allow for additional flexibility, this issue should address the following items:
1. Allow for the scope token to be extracted, its signature validated, independent of whether scope validation is enabled / disabled and its claims extracted.
2. Allow for the configuration to extract and validate custom tokens from the request, in case a developer has a use case where such tokens are beneficial. A custom location in the header would have to be pre-configured with the header location to look into

**Comment by stevehu** [comment]
If my memory serves, we only extract custom claims from the Subject token because customer claims only associate with the login user from the originator. I am not sure if we should support custom claims from additional tokens.

**Comment by ddobrin** [comment]
We are extracting the claims from both Subject and Scope Token and store them in AUDIT_INFO, under "subject_claims", respectively "access_claims". That change was made a long time ago.

The claims from the Subject token identify the original caller, and the Subject token is propagated in an API chain.

The claims from the Scope Token are claims set by the immediate caller.

To solve this issue, addressing what is listed above in [1] is sufficient, for simplicity reasons.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add flexibility to JWT token validation in openapi-security light-rest-4j 1.6.x](https://trello.com/c/KDD1s6wj/418-add-flexibility-to-jwt-token-validation-in-openapi-security-light-rest-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add flexibility to JWT token validation in openapi-security](https://trello.com/c/aQnBCWsy/419-add-flexibility-to-jwt-token-validation-in-openapi-security)

**Comment by ddobrin** [comment]
My client is using this flag and, unless there is a compelling reason for changing, it might be better to leave it as is.

**Comment by stevehu** [comment]
@jsu216 When there are too many flags to control fine-grained behaviors, it is very easy to make users confused. Do you think we can make the comment in the config file more clear to resolve the problem?

**Comment by jsu216** [comment]
I am not asking for any code change. Just want to make sure that the comment or document should reflect what the behaviour is supposed to be.

**Comment by stevehu** [comment]
@jsu216 Any suggestions on how to update the comment and the document?

**Comment by jsu216** [comment]
@stevehu Can you give me the link to the document regarding this? What I found was from the comments in openapi-security.yml at the test resource folder, which is the official doc.

**Comment by stevehu** [comment]
Yes. The most important place is inline comments in the openapi-security.yml file. Also, this document link needs to be in sync. https://doc.networknt.com/style/light-rest-4j/openapi-security/
