### ISSUE TITLE
Support parameterization of handling nullable fields

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-rest-4j#113]
Issue #183 in json-schema-validator addresses the handling of nullable fields.

A configuration change in SchemaValidatorsConfig allows this behaviour to be controlled using flags.

The openapi-validator.yml should allow the setting of the `handleNullableField`in a flexible manner

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support parameterization of handling nullable fields 1.6.x](https://trello.com/c/6ZlUvPYp/454-support-parameterization-of-handling-nullable-fields-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support parameterization of handling nullable fields master](https://trello.com/c/Jl8hR0Zj/455-support-parameterization-of-handling-nullable-fields-master)
