### ISSUE TITLE
openapi-validation should only validate json type request for request body validation

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-rest-4j#117]
If we expect some other data type in the request body. for example text/csv, XML, plain text.
The openapi specification defined as below as sample:

requestBody:
  description: The contents of the csv file to be uploaded. Expected UTF-8 format.
  required: true
  content:
    text/csv:
      schema:
        type: string

And user indicated the header content-type is text/csv.

When user submit request, will get validation error:

{"statusCode":400,"code":"ERR11014","message":"VALIDATOR_REQUEST_BODY_MISSING","description":"Method post on path /user/async/bulkimport requires a request body. None found.","severity":"ERROR"}

So for the request body validation, we can skip it if the content type indicated and it is not  "application/json"

**Comment by stevehu** [comment]
I think we still need to validate the request in the case that text/csv is the content type. The only thing that we need to skip is the schema validation for the body. Header, query parameters, and path parameters all need to be validated. What do you think?

**Comment by chenyan71** [comment]
@stevehu 
As you suggested, only skip request body validation if the content type is indicated as non-application/json.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openapi-validation should only validate json type request for request body validation](https://trello.com/c/fcCri7UQ/486-openapi-validation-should-only-validate-json-type-request-for-request-body-validation)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openapi-validation should only validate json type request for request body validation master](https://trello.com/c/ZQ4lnD9Y/487-openapi-validation-should-only-validate-json-type-request-for-request-body-validation-master)
