### ISSUE TITLE
Status being overwritten by new implementation of setExchangeStatus

### ISSUE THREAD

**Issue by malky** [networknt/light-rest-4j#119]
The new 1.6.11 release contains a new method called setExchangeStatus, this method re-creates the Status object in LightHttpHandler.java but sends empty arguments which causes the error placeholders in the status.yml to not be replaced.

https://github.com/networknt/light-rest-4j/blob/1ea5b46658ddb3f8af57e7803d20de42aa3f1618/openapi-validator/src/main/java/com/networknt/openapi/ValidatorHandler.java#L84-L89

The Status object had already been created and it evaluates fine. So either use the original status object from L84 or pass the args to the setExchangeStatus so the Status object can be evaluated properly.

The following is the response with a schema error, the placeholder doesn't get replaced because of the arguments missing when re-creating the status, ideally the Status object should only be created once:

```
{
    "statusCode": 400,
    "code": "ERR11004",
    "message": "VALIDATOR_SCHEMA",
    "description": "Schema Validation Error - %s",
    "severity": "ERROR"
}
```

**Comment by stevehu** [comment]
https://github.com/networknt/light-4j/issues/637

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Status being overwritten by new implementation of setExchangeStatus 1.6.x](https://trello.com/c/EoLr3GVO/518-status-being-overwritten-by-new-implementation-of-setexchangestatus-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Status being overwritten by new implementation of setExchangeStatus master](https://trello.com/c/W1u7Ik2W/519-status-being-overwritten-by-new-implementation-of-setexchangestatus-master)
