### ISSUE TITLE
ValidatorHandler masking status returned from validation with new status

### ISSUE THREAD

**Issue by pradeepth** [networknt/light-rest-4j#121]
In `handleRequest` method of `ValidationHandler`, following is the block of code that needs to be fixed

```
Status status = requestValidator.validateRequest(requestPath, exchange, openApiOperation);
if(status != null) {
    setExchangeStatus(exchange, status.getCode());
    if(config.logError) logger.error("ValidationError:" + status.toString());
    return;
}
```

When `status` is already populated with arguments, it is replaced with new `status` again because `setExchangeStatus(exchange, status.getCode());` is not using the generated `status` object and is not providing the actual arguments that are needed to format the `description` in the `status` object. 

To resolve this, `setExchangeStatus(exchange, status.getCode());` should be replaced with `setExchangeStatus(exchange, status);`

**Comment by stevehu** [comment]
@pradeepth Thanks a lot for raising it up. This was reported by another contributor today and it is addressed in the release 1.6.13 (released) and 2.0.9 (pending). Could you please confirm if it is the same as https://github.com/networknt/light-rest-4j/issues/119? Happy New Year!!!!

**Comment by pradeepth** [comment]
Thank you @stevehu for your prompt response. Yes the issue #119 is same as the one I raised. Happy New Year!

**Comment by stevehu** [comment]
Cool. Thanks a lot for your confirmation. Please stay tuned for the new release.
