### ISSUE TITLE
Fix HTTP 404 on documentation

### ISSUE THREAD

**Issue by ivanviragine** [networknt/light-rest-4j#13]
I'm trying to read the documentation, but I'm getting 404 on every topic:

https://networknt.github.io/light-rest-4j/ < OK

https://networknt.github.io/light-rest-4j/getting-started/ < 404
https://networknt.github.io/light-rest-4j/design/ < 404
...

**Comment by stevehu** [comment]
@ivanviragine Thanks for pointing this out. The document site for light-rest-4j is still working in progress and more content will be added to it. Also, a lot of generic information can be found in https://networknt.github.io/light-4j/index.html at the moment. 

This morning, I have spent several hours to update light-rest-4j documents and now all links should have something there. Please review and let me know if anything needs to be added/updated.

**Comment by ivanviragine** [comment]
Thanks @stevehu!

As soons as I get a chance, I'll review and let you know!
