### ISSUE TITLE
OpenApiHandler overwrite auditing info

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-rest-4j#160]
in OpenApiHandler
exchange.putAttachment(AttachmentConstants.AUDIT_INFO, auditInfo);
it will overwrite an existing audit info

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/networknt/light-rest-4j/issues/160 light-rest-4j master](https://trello.com/c/fiD0Q6UB/906-https-githubcom-networknt-light-rest-4j-issues-160-light-rest-4j-master)
