### ISSUE TITLE
move JWTVerifier from static to constructor

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-rest-4j#173]
related to https://github.com/networknt/light-4j/issues/897 
if there's an exception in JwtVerifier, the server won't stop. Thus move it from static block to constructor

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [move JWTVerifier from static to constructor light-rest-4j master](https://trello.com/c/dMPu5QZ3/948-move-jwtverifier-from-static-to-constructor-light-rest-4j-master)
