### ISSUE TITLE
Return "ERR11018" if  has a return content in the response, but no schema defined

### ISSUE THREAD

**Issue by edinardo** [networknt/light-rest-4j#176]
On the ResponseValidator (openapi-validator) at the method:
```java
public Status validateResponseContent(Object responseContent, OpenApiOperation openApiOperation, String statusCode, String mediaTypeName) {
    //try to convert json string to structured object
    if(responseContent instanceof String) {
        responseContent = convertStrToObjTree((String)responseContent);
    }
    JsonNode schema = getContentSchema(openApiOperation, statusCode, mediaTypeName);
    //if cannot find schema based on status code, try to get from "default"
    if(schema == null || schema.isMissingNode()) {
        // if corresponding response exist but also does not contain any schema, pass validation
        if (openApiOperation.getOperation().getResponses().containsKey(String.valueOf(statusCode))) {
            return null;
        }
        schema = getContentSchema(openApiOperation, DEFAULT_STATUS_CODE, mediaTypeName);
        // if default also does not contain any schema, pass validation
       if (schema == null || schema.isMissingNode()) return null;
    }
    if ((responseContent != null && schema == null) ||
            (responseContent == null && schema != null)) {
        return new Status(VALIDATOR_RESPONSE_CONTENT_UNEXPECTED, openApiOperation.getMethod(), openApiOperation.getPathString().original());
    }
    config.setTypeLoose(false);
    config.setHandleNullableField(ValidatorHandler.config.isHandleNullableField());
    return schemaValidator.validate(responseContent, schema, config);
}
```
I don't see how is possible to `return new Status(VALIDATOR_RESPONSE_CONTENT_UNEXPECTED, openApiOperation.getMethod(), openApiOperation.getPathString().original());` as the code will never reach here with `schema == null`.

This will be useful to detect cases where for instance, doesn't have a default response, and the response status "mistakenly" uses a status code that is not defined in the specs.

**Comment by stevehu** [comment]
@edinardo Thanks a lot for raising this issue. The request validation works very well and most users are using it. However, the response validation is not being used by anyone I know. We had several discussions between the team members and most of them are leaning to put response validation to the client-side. By putting it on the server-side, we don't know how to report the error along with the normal response from the API. Let me know if you have any suggestions to get it working. Thanks.

**Comment by stevehu** [comment]
I think I found a defect after reviewing the code. After the refactoring, we forgot to initialize the OpenApiHelper with the specification in the constructor. Please review the PR. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [initialize the OpenApiHelper for the response validator light-rest-4j master](https://trello.com/c/bWriOCZJ/975-initialize-the-openapihelper-for-the-response-validator-light-rest-4j-master)

**Comment by edinardo** [comment]
> @edinardo Thanks a lot for raising this issue. The request validation works very well and most users are using it. However, the response validation is not being used by anyone I know. We had several discussions between the team members and most of them are leaning to put response validation to the client-side. By putting it on the server-side, we don't know how to report the error along with the normal response from the API. Let me know if you have any suggestions to get it working. Thanks.

Thanks for the quick handling and sorry for the delayed response. 
Since we have full control of the content response, I agree that the response validation should be done on the client-side and tests.
I will work with my team to go in that direction and maybe implement a filter to be enabled only on development time as a sanity check.
