### ISSUE TITLE
OpenApiHandler openapi inject yaml cache to openapi and caused the exception

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-rest-4j#183]
When the TestServer load for different test cases, the openapi inject yaml merged multiple times since the configCache, need ignore cache when the OpenApiHandler  load the inject and openapi

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OpenApiHandler openapi inject yaml cache to openapi and caused the exception light-rest-4j master](https://trello.com/c/4AEGWfcg/1120-openapihandler-openapi-inject-yaml-cache-to-openapi-and-caused-the-exception-light-rest-4j-master)
