### ISSUE TITLE
com.fizzed.rocker.runtime.RockerRuntime - Rocker template reloading not activated

### ISSUE THREAD

**Issue by anujku123** [networknt/light-rest-4j#22]
I am new in light4j and follow this link   https://networknt.github.io/light-rest-4j/tutorial/petstore  and bellow steps  . But can not able to run project please help me how can i deploy this project
     
      1. mkdir networknt
       2. cd networknt/
       3. git clone https://github.com/networknt/light-example-4j
       4. git clone https://github.com/networknt/light-codegen.git
       5. git clone https://github.com/networknt/light-oauth2.git
       6. git clone https://github.com/networknt/light-docker.git
       7. git clone https://github.com/networknt/model-config.git
       8. cd light-example-4j/rest/
       9. mv petstore petstore.bak

       Now inside light-codegen directory 

       10. cd light-codegen
 
       11. mvn install -DskipTests

       12. java -jar codegen-cli/target/codegen-cli.jar -f light-rest-4j -o /home/xyz/light4j-code/networknt/light-example-4j/rest/petstore -m /home/xyz/light4j-code/networknt/model-config/rest/petstore/2.0.0/swagger.json -c /home/xyz/light4j-code/networknt/model-config/rest/petstore/2.0.0/config.json
    
     Note : i have got this message on run above commend :

     /home/xyz/light4j-code/networknt/light-example-4j/rest/petstore11:12:43.192 [main] INFO com.fizzed.rocker.runtime.RockerRuntime 
         - Rocker version 0.22.0 11:12:43.198 [main] INFO com.fizzed.rocker.runtime.RockerRuntime - Rocker template reloading not activated

      Now goto inside directory

      13. cd light-example-4j/petstore
  
      14. mvn install exec:exec

       On running below command
      15. curl localhost:8080/v2/pet/111
       
        I got result :

       Failed to connect to localhost port 8080: Connection refused

   Please help me how can i setup light4j project on my local machine

**Comment by stevehu** [comment]
@anujku123 Thanks a lot to bring up this issue. In release 1.5.0, we have disabled the http and default to https in server.yml config file. Please use the following command to access the server. The tutorial will be updated shortly. 

```
curl -k https://localhost:8443/v2/pet/111
```
