### ISSUE TITLE
Nullable not supported per openapi 3 spec?

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-rest-4j#50]
https://swagger.io/docs/specification/data-models/data-types/

It seems the nullable field is ignored when validating requests.

Following is spec:

```json
# schema
"helloBody": {
  "required": [],
  "properties": {
    "name": {
      "type": "string",
      "nullable": true
    }
  }
 }
```

Given this, how would we go about creating a nullable string?

**Comment by stevehu** [comment]
The case is pretty complicated as nullable can be applied to all types. We need to have a discussion on this topic.
