### ISSUE TITLE
Configured class: com.foo.reportListener.handler.SpecYamlGetHandler has not been found

### ISSUE THREAD

**Issue by farrukhnajmi** [networknt/light-rest-4j#61]
Using latest master 9dc732f27a46692275ac79a539f3a80b4bbcb05d of lite-codegen I generated a project.

1. I build it fine with `mvn install`
1. I run it mvn exec:exec with no change I get the following exception:

```
19:25:32.562 [main] com.foo.report-listener-1.0.1  ERROR com.networknt.server.Server main - Server is not operational! Failed with exception
java.lang.RuntimeException: Configured class: com.foo.reportListener.handler.SpecYamlGetHandler has not been found
        at com.networknt.handler.Handler.splitClassAndName(Handler.java:445)
        at com.networknt.handler.Handler.initStringDefinedHandler(Handler.java:359)
        at com.networknt.handler.Handler.initHandlers(Handler.java:71)
        at com.networknt.handler.Handler.init(Handler.java:53)
        at com.networknt.server.Server.start(Server.java:151)
        at com.networknt.server.Server.main(Server.java:123)
```

**Comment by miklish** [comment]
Did you include com.foo.reportListener.handler.SpecYamlGetHandler in handler.yml? You need to specify all handler classes in handler.yml sp the Dependency Injector can load it during startup.

**Comment by farrukhnajmi** [comment]
Yes its in there, I am simply running the project as generated with no code changes by me.

**Comment by stevehu** [comment]
@farrukhnajmi I have tried to compile and start the latest https://github.com/networknt/light-example-4j/tree/master/rest/openapi/petstore without any issue. Also, is this class SpecYamlGetHandler your own? I cannot find any reference from our source code.

**Comment by farrukhnajmi** [comment]
It seems that my adding the following in my openapi.yaml caused the problem:

```
paths:
  /spec.yaml:
    get:
      exec: spec

  /specui.html:
    get:
      exec: swaggerui
```

I did this based on the possibly incorrect or misleading docs at:

https://doc.networknt.com/style/light-rest-4j/openapi-display/#path-for-specification-display

When I take it out all is well. Thanks.
