### ISSUE TITLE
openapi helper throws an exception when servers not defined

### ISSUE THREAD

**Issue by zabooma** [networknt/light-rest-4j#62]
This is related to #184 in codegen.
If servers section is omitted from openapi (or it is there but url is not defined) openapi helper throws an exception.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openapi helper throws an exception when servers not defined](https://trello.com/c/91wpuVE6/23-openapi-helper-throws-an-exception-when-servers-not-defined)
