### ISSUE TITLE
Runtime error on GET serialised query objects

### ISSUE THREAD

**Issue by Dasanko** [networknt/light-rest-4j#67]
When a GET endpoint parameter is an object, the validation fails and returns a runtime error (statusCode 500).

Steps to reproduce:
Clone and compile https://github.com/networknt/light-codegen/
Using the attached files; java -jar light-codegen/codegen-cli/target/codegen-cli.jar -f openapi -o testproject -m testproject.yaml -c config.json
Run testproject
The following calls will all fail:
curl -k -X GET https://localhost:8099/api/testEndPoint?TestObject={testProperty=testing}
curl -k -X GET https://localhost:8099/api/testEndPoint?TestObject[testProperty]=testing
curl -k -X GET https://localhost:8099/api/testEndPoint?TestObject=testProperty,testing
curl -k -X GET https://localhost:8099/api/testEndPoint?testProperty=testing

The second, third and fourth cases should be supported according to:
https://swagger.io/docs/specification/describing-parameters/#query-parameters
https://swagger.io/docs/specification/serialization/

[config.json.txt](https://github.com/networknt/light-rest-4j/files/2679311/config.json.txt)
[testproject.yaml.txt](https://github.com/networknt/light-rest-4j/files/2679312/testproject.yaml.txt)

**Comment by stevehu** [comment]
@Dasanko I have marked this issue as Help Wanted and hope one of the community member to pick it up. Thanks for bringing it up.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generate config file for each handler wired into the handler chain](https://trello.com/c/g7c2loxC/85-generate-config-file-for-each-handler-wired-into-the-handler-chain)

**Comment by Dasanko** [comment]
The issue has been solved in the refered commits.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Runtime error on GET serialised query objects](https://trello.com/c/tV3aCA1J/253-runtime-error-on-get-serialised-query-objects)
