### ISSUE TITLE
JwtVerifyHandler needs to handle properly the value returned by the Config module

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-rest-4j#70]
The Handler, in isEnabled(), needs to handle the isEnabld flag regardless if it is returned as an Object or primitive boolean.

Change is:
    @Override
    public boolean isEnabled() {
        Object object = config.get(JwtHelper.ENABLE_VERIFY_JWT);
        return object != null && Boolean.valueOf(object.toString()) ;
    }

**Comment by stevehu** [comment]
@ddobrin This is a very good catch. The old code is based on a very restricted assumption and is error-prone. If this works, we need to review other handlers as there are a lot of enabled flags. Also, we might need to review other data types other than strings. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JwtVerifyHandler needs to handle properly the value returned by the Config module](https://trello.com/c/Jn5YTWIb/75-jwtverifyhandler-needs-to-handle-properly-the-value-returned-by-the-config-module)
