### ISSUE TITLE
Fix/test case validation error when response is empty

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-rest-4j#76]
Currently, when response is empty in test case, the validator would use default schema to validate this empty response which would lead to error validation.

Related PR by @BalloonWen: https://github.com/networknt/light-codegen/pull/240

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Uncompilable code generation caused by invalid variable name](https://trello.com/c/uS0kCIhy/112-uncompilable-code-generation-caused-by-invalid-variable-name)
