### ISSUE TITLE
The links in README.md are pointed to a "localhost" host.

### ISSUE THREAD

**Issue by xiaolongtang** [networknt/light-rest-4j#78]
Hi 
Thank you for providing such awesome framework. I am trying to get hands on it. But the links in the markdown file are incorrect. Could you please fix it?

Thanks

**Comment by stevehu** [comment]
@xiaolongtang Thanks a lot for bringing it up. I have fixed the three links in the README file. There are several links in the readme with supporting channels. Please let us know if you have ideas to improve the platform or encounter any issue.

**Comment by xiaolongtang** [comment]
@stevehu 
Thank you for your prompt response. They all work fine now.
