### ISSUE TITLE
 light-rest-4j is not support json format 

### ISSUE THREAD

**Issue by shingle2302** [networknt/light-rest-4j#83]
I execute "java -jar codegen-cli/target/codegen-cli.jar -f openapi -o /tmp/openapi-json -m light-rest-4j/src/test/resources/openapi.json -c light-rest-4j/src/test/resources/config.json
" to generate an example,when i request specui.htm, NPE occurs.
![image](https://user-images.githubusercontent.com/20883097/55625851-85c1c100-57dc-11e9-8fcc-340f90161dd8.png)

**Comment by jang675953** [comment]
![image](https://user-images.githubusercontent.com/20883097/55626185-64150980-57dd-11e9-92b7-a88d7f577b4d.png)
